import type { Metadata } from "next";
import "@styles/globalStyles.scss";
import ClientWrapper from "./clientWrapper";

export const metadata: Metadata = {
  title: "Fast Appliance Repair Pro",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ClientWrapper>{children}</ClientWrapper>
      </body>
    </html>
  );
}
